title: Vitte
subtitle: The Vitte Language
baseurl: ""
url: ""
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
permalink: pretty

collections:
  chapters:
    output: true
    permalink: /book/:name/

defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      path: ""
      type: chapters
    values:
      layout: chapter

include:
  - pages

exclude:
  - Gemfile
  - Gemfile.lock
  - scripts
  - vendor
  - node_modules
